Feature/si 2427 apiv2 consolidate analytics endpoint for dinc service in api
DIMO-Network/devices-api pull request #304
Opened 2024-04-10 00:12 UTC by 0xdev22

# Proposed Changes

### Impacted Routes

### Caveats

2024-04-10 19:06 UTC, KevinJoiner requested changes

2024-04-10 19:06 UTC, KevinJoiner commented on internal/controllers/user_devices_controller_v2.go
> +func (udc *UserDevicesControllerV2) GetRange(c *fiber.Ctx) error {
It looks like most of this is duplicate code from the v1/GetRange. If this is true, can you move it to a single function that both endpoints call?

2024-04-17 14:52 UTC, Allyson-English approved these changes

2024-04-17 14:52 UTC, Allyson-English commented on cmd/devices-api/api.go
> +	vehiclePrivilegeV2Routes := app.Group("/v2/vehicles/:tokenID", privilegeAuth)
nit: could shorten this var name to `vPriv2`

2024-04-23 18:15 UTC, closed without merging