Change route for fetching error codes
DIMO-Network/devices-api pull request #40
Opened 2023-03-20 18:24 UTC by 0xdev22

# Proposed Changes

### Impacted Routes

### Caveats

2023-03-20 21:59 UTC, elffjs requested changes

2023-03-20 21:59 UTC, elffjs commented on internal/controllers/device_data_controller.go
>  		qm.Load(models.UserDeviceRels.ErrorCodeQueries, qm.OrderBy("created_at desc")),
```suggestion
		qm.Load(models.UserDeviceRels.ErrorCodeQueries, qm.OrderBy(models.ErrorCodeQueryColumns.CreatedAt + " DESC")),
```
Minor suggestion.

2023-03-22 08:20 UTC, 0xdev22 commented on internal/controllers/device_data_controller.go
>  	).All(c.Context(), udc.DBS().Reader)
Using .`One` here only returns one of the stored queries for the userDevice and since we can have multiple error codes it won't work in this case

2023-03-22 11:45 UTC, elffjs commented on internal/controllers/device_data_controller.go
>  	).All(c.Context(), udc.DBS().Reader)
The top level table is `user_devices`. I don’t think `.One` is going to constrain the load on the relation.

2023-03-22 11:52 UTC, elffjs requested changes

2023-03-22 11:52 UTC, elffjs commented on cmd/devices-api/main.go
> +		/* if settings.EnablePrivileges {
Is this left behind from local debugging? Could we get rid of it?

2023-03-22 11:52 UTC, elffjs commented on internal/controllers/device_data_controller.go
>  	for _, userDevice := range userDevices {
I think that we’re iterating over a list of vehicles for a one-vehicle endpoint should give us pause!

2023-03-22 11:52 UTC, elffjs commented on internal/controllers/device_data_controller.go
>  func (udc *UserDevicesController) GetUserDevicesErrorCodeQueries(c *fiber.Ctx) error {
Oh maybe we should change the function name too—`GetUserDeviceErrorCodeQueries`?

2023-03-22 11:52 UTC, elffjs commented on internal/controllers/device_data_controller.go
>  	return c.JSON(resp)
Could we put this list in a wrapper object? Just in case.

2023-03-22 11:52 UTC, elffjs commented on internal/controllers/device_data_controller_test.go
> -			fmt.Sprintf(`{"%s":[{"errorCodes":["P0017","P0016"],"description":"1. P0113 - Engine Coolant Temperature Circuit Malfunction: This code indicates that the engine coolant temperature sensor is send
Hmm, I wonder why this is failing.

2023-03-22 19:04 UTC, merged